out_dir: results
metric_best: mae
metric_agg: argmin
wandb:
  use: True
  project: ZINC
  entity: position-encoding
  name: spd-ign-new
dataset:
  format: PyG-ZINC
  name: subset
  task: graph
  task_type: regression
  transductive: False
  node_encoder: True
  node_encoder_name: TypeDictNode+RPETransformerBias+IGNRPEEncoder
  node_encoder_num_types: 28
  node_encoder_bn: False
  edge_encoder: False
  edge_encoder_name: TypeDictEdge
  edge_encoder_num_types: 4
  edge_encoder_bn: False
posenc_RPE:
  enable: True
  num_in_degrees: 64
  num_out_degrees: 64
  shortest_path_distance: True
  num_rpes: 1
ign_encoder:
  enable: True
  num_hidden_layers: 6
  hidden_dim: 48
  out_dim: 80
train:
  mode: custom
  batch_size: 32
  eval_period: 1
  ckpt_period: 100
model:
  type: RPETransformer
  loss_fun: l1
  edge_decoding: dot
  graph_pooling: graph_token
rpe_transformer:
  num_layers: 8
  num_heads: 8
  embed_dim: 80
  dropout: 0.0
  attention_dropout: 0.1
  mlp_dropout: 0.1
  input_dropout: 0.1
  use_add_bias: False
  use_mult_bias: False
gnn:
  head: graphormer_graph
  layers_pre_mp: 0
  layers_post_mp: 3  # Not used when `gnn.head: san_graph`
  dim_inner: 80  # `gt.dim_hidden` must match `gnn.dim_inner`
  batchnorm: True
  act: relu
  dropout: 0.0
  agg: mean
  normalize_adj: False
optim:
  clip_grad_norm: True
  clip_grad_norm_value: 5.0
  optimizer: adamW
  weight_decay: 0.01
  base_lr: 0.001 # 0.0002
  max_epoch: 1000 # 10000
  scheduler: polynomial_with_warmup
