out_dir: results
metric_best: accuracy
wandb:
  use: True
  project: CSL
  entity: position-encoding
  name: rwse_deepsets
dataset:
  split_mode: cv-stratifiedkfold-5
  format: PyG-GNNBenchmarkDataset
  name: CSL
  task: graph
  task_type: classification
  transductive: False
  node_encoder: True
  node_encoder_name: DeepSetsAPEEncoder+RPETransformerBias
  node_encoder_bn: False
  edge_encoder: False
  edge_encoder_name: LinearEdge
  edge_encoder_bn: False
train:
  mode: custom
  batch_size: 32 # full batch
  eval_period: 1
  enable_ckpt: True  # Checkpointing can now be disabled to save I/O when e.g. just benchmarking.
  ckpt_best: True  # WARNING: Checkpoint every epoch a better model is found may increase I/O significantly.
#  ckpt_period: 100  # Follow set checkpointing schedule
model:
  type: RPETransformer
  loss_fun: cross_entropy
  edge_decoding: dot
  graph_pooling: graph_token
rpe_transformer:
  num_layers: 4
  num_heads: 4
  num_kernels: 8
  embed_dim: 8
  dropout: 0.0
  attention_dropout: 0.1
  mlp_dropout: 0.1
  input_dropout: 0.1
  update_bias_each_layer: True
posenc_RPE:
  enable: True
  num_in_degrees: 16
  num_out_degrees: 16
  num_rpes: 8
posenc_RWSE:
  enable: True
  kernel:
    times_func: range(1,21) 
deepsets_ape_encoder:
  enable: True
  input_dim: 20
  hidden_dim: 32
  output_dim: 8
  num_hidden_layers: 3
gnn:
  head: graphormer_graph
  layers_pre_mp: 0
  layers_post_mp: 3  # Not used when `gnn.head: san_graph`
  dim_inner: 8  # `gt.dim_hidden` must match `gnn.dim_inner`
  batchnorm: True
  act: relu
  dropout: 0.0
  agg: mean
  normalize_adj: False
optim:
  clip_grad_norm: True
  clip_grad_norm_value: 5.0
  optimizer: adamW
  weight_decay: 0.01
  base_lr: 0.01
  max_epoch: 2000
  scheduler: polynomial_with_warmup
  num_warmup_epochs: 50
